bereal/apps/core/urls.py
from django.conf.urls.defaults import patterns, url, include

from .views import ping, authenticated_ping

urlpatterns = patterns('',
    url(r'^ping/$', ping, name="core_ping"),
    url(r'^auth_ping/$', authenticated_ping, name="core_ping"),
)

bereal/apps/todos/urls.py
from django.conf.urls.defaults import patterns, url, include

from .views import index, my_collections

urlpatterns = patterns('',
    url(r'^$', index, name="todos_index"),
    url(r'^todos/$', my_collections, name="todos_mycollections"),
)

bereal/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.defaults import patterns, url, include

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'', include('bereal.apps.core.urls')),
    (r'', include('bereal.apps.todos.urls')),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG and settings.MEDIA_ROOT:
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

bereal/apps/core/models.py
from django.db import models

# Create your models here.

bereal/apps/realtime/models.py
from django.db import models

# Create your models here.

bereal/apps/todos/models.py
from django.db import models


class Collection(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey("auth.User")

    def __unicode__(self):
        return u"{0} for {1}".format(self.name, self.user)

class Item(models.Model):
    parent = models.ForeignKey(Collection)
    name = models.CharField(max_length=255)
    is_done = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

bereal/apps/core/views.py
import json

from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


def ping(request):
    return HttpResponse("pong")


@login_required
def authenticated_ping(request):
    user_id = request.user.id
    return HttpResponse(json.dumps({"user_id": user_id,
                                    "channels": ["chan_all",
                                                 "chan_user_%s" % user_id]}))

bereal/apps/realtime/views.py
# Create your views here.

bereal/apps/todos/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Collection

def index(request):
    return render(request, "todos/index.html", {})

@login_required
def my_collections(request):
    mycollections = Collection.objects.filter(user=request.user)
    return render(request, "todos/my_collections.html", {"mycollections": mycollections})

bereal/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block head_title %}{% endblock %}</title>
    <meta charset="utf-8">
</head>
<body>

<div id="container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

bereal/templates/todos/index.html
{% block content %}
    <h1>Todos</h1>
    <a href="{% url todos_mycollections %}">My todo lists</a>
{% endblock %}

bereal/templates/todos/my_collections.html
{% block content %}
{% for collection in mycollections %}
    <h2>{{ collection.name }}</h2>
    <ul>
        {% for item in collection.item_set.all %}
        <li>{{ item.name }} </li>
        {% endfor %}
    </ul>
{% endfor %}
{% endblock %}